### ISSUE TITLE
Outdated URL to ngaas

### ISSUE THREAD

**Issue by agrrh** [imjacobclark/jacobclark.xyz#1]
Hello there

Probably you should add "api" part here:

`src/main/resources/com/uk/jacob/views/partials/homepage/content-sections/projects.mustache`

It's a great service :)

**Comment by imjacobclark** [comment]
@agrrh Thanks! I fixed this yesterday in https://github.com/imjacobclark/jacobclark.xyz/commit/dee8c3d75d25d1a30138044dda56fb84eedf5a74!
